#pragma once

#define CONFIG_PN532_RX 5
#define CONFIG_PN532_TX 9

#define CONFIG_MAX_CARDS 512
// Random 16 bit value for CRC calculation
#define CONFIG_CRC_START_VALUE 46380

#define CONFIG_DOOR_OPEN_TIME_MS 2000
#define CONFIG_DOOR_PIN 1
#define CONFIG_DOOR_ACTIVE_LOW true

#define CONFIG_LED_STRIP_PIN 8
#define CONFIG_LED_STRIP_LENGTH 1
#define CONFIG_LED_STRIP_BRIGHTNESS 6

#define CONFIG_W5500_SCLK 6
#define CONFIG_W5500_MISO 2
#define CONFIG_W5500_MOSI 7
#define CONFIG_W5500_SS 3
#define CONFIG_W5500_INT 4
